# Getting Started

In [2]:
import pandas as pd
from matplotlib.dates import SUNDAY, FRIDAY
from pandas.conftest import ascending

df= pd.DataFrame([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20],[21,22,23,24]], columns=['a','b','c','d'])

In [20]:
df

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       6 non-null      int64
 1   b       6 non-null      int64
 2   c       6 non-null      int64
 3   d       6 non-null      int64
dtypes: int64(4)
memory usage: 324.0 bytes

In [15]:
df.describe()

               a          b          c          d
count   6.000000   6.000000   6.000000   6.000000
mean   11.000000  12.000000  13.000000  14.000000
std     7.483315   7.483315   7.483315   7.483315
min     1.000000   2.000000   3.000000   4.000000
25%     6.000000   7.000000   8.000000   9.000000
50%    11.000000  12.000000  13.000000  14.000000
75%    16.000000  17.000000  18.000000  19.000000
max    21.000000  22.000000  23.000000  24.000000

In [35]:
df.shape

(6, 4)

In [37]:
df.size

24

# Loading in Dataframes from Files

In [8]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
results = pd.read_parquet('./data/results.parquet')
bios = pd.read_csv('./data/bios.csv')

In [40]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [50]:
results.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

# Acessing Data with Pandas

In [13]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [24]:
coffee.iloc[2:7,0:3]

         Day Coffee Type  Units Sold
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40

In [34]:
coffee.index = coffee["Day"]
(coffee.tail())

               Day Coffee Type  Units Sold
Day
Friday      Friday       Latte          35
Saturday  Saturday    Espresso          45
Saturday  Saturday       Latte          35
Sunday      Sunday    Espresso          45
Sunday      Sunday       Latte          35

In [43]:
coffee.loc["Friday":"Sunday"]

               Day Coffee Type  Units Sold
Day
Friday      Friday    Espresso          45
Friday      Friday       Latte          35
Saturday  Saturday    Espresso          45
Saturday  Saturday       Latte          35
Sunday      Sunday    Espresso          45
Sunday      Sunday       Latte          35

In [45]:
coffee.Day#podemos acessar os dados assim de uma coluna se for apenas uma palavra, se for duas podemos usar [] os brackets
coffee["Units Sold"]#Como nesse exemplo

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Thursday     40
Thursday     30
Friday       45
Friday       35
Saturday     45
Saturday     35
Sunday       45
Sunday       35
Name: Units Sold, dtype: int64

In [47]:
coffee.sort_values("Units Sold", ascending=False)

                 Day Coffee Type  Units Sold
Day
Saturday    Saturday    Espresso          45
Friday        Friday    Espresso          45
Sunday        Sunday    Espresso          45
Thursday    Thursday    Espresso          40
Wednesday  Wednesday    Espresso          35
Saturday    Saturday       Latte          35
Sunday        Sunday       Latte          35
Friday        Friday       Latte          35
Tuesday      Tuesday    Espresso          30
Thursday    Thursday       Latte          30
Monday        Monday    Espresso          25
Wednesday  Wednesday       Latte          25
Tuesday      Tuesday       Latte          20
Monday        Monday       Latte          15

In [70]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=[0,1])

                 Day Coffee Type  Units Sold
Day
Friday        Friday    Espresso          45
Saturday    Saturday    Espresso          45
Sunday        Sunday    Espresso          45
Thursday    Thursday    Espresso          40
Wednesday  Wednesday    Espresso          35
Friday        Friday       Latte          35
Saturday    Saturday       Latte          35
Sunday        Sunday       Latte          35
Tuesday      Tuesday    Espresso          30
Thursday    Thursday       Latte          30
Monday        Monday    Espresso          25
Wednesday  Wednesday       Latte          25
Tuesday      Tuesday       Latte          20
Monday        Monday       Latte          15

In [ ]:
#Também podemos interagir com o for, porem perdemos a performance da memoria é ficaria muito mais pesado
# for index, row in coffee.iterrows():
#     print(index)
#     print(row)
#     print("\n\n\n")

# Filtering Data

In [62]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [103]:
greater_210cm = bios.loc[bios['height_cm']>210, ['born_date','name','born_country','height_cm'] ]
greater_210cm

         born_date                   name born_country  height_cm
5089    1957-06-19     Viktor Pankrashkin          RUS      220.0
5572    1968-12-07        Santiago Aldama          ESP      213.0
5583    1963-01-26   Paulinho Villas Boas          BRA      217.0
5599    1945-06-14      Vladimir Andreyev          RUS      215.0
5609    1965-06-02        Franjo Arapović          NaN      211.0
...            ...                    ...          ...        ...
140298  1992-09-11       Aaron Geramipoor          GBR      214.0
141018  1994-10-13          Yuta Watanabe          JPN      215.0
142044  1995-12-15          Jahlil Okafor          USA      211.0
142930  1994-10-10             Mike Tobey          USA      213.0
143712  1988-01-19           JaVale McGee          USA      213.0

[150 rows x 4 columns]

In [87]:
bios.loc[(bios['height_cm']>205)&(bios['born_country']=='BRA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5598,5621,Israel,1960-01-17,Salvador,Bahia,BRA,Brazil,206.0,110.0,NaN
5992,6018,Olívia,1974-02-03,Rio de Janeiro,Rio de Janeiro,BRA,Brazil,211.0,100.0,NaN
6077,6103,Rolando,1964-05-24,Curitiba,Paraná,BRA,Brazil,214.0,105.0,NaN
6554,6587,Sílvio,1960-03-17,São Paulo,São Paulo,BRA,Brazil,207.0,83.0,NaN
7016,7052,Josuel,1970-06-14,Barueri,São Paulo,BRA,Brazil,207.0,115.0,NaN
7074,7111,Paulo da Silva,1963-07-21,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
120364,122261,Anderson Varejão,1982-09-28,Colatina,Espírito Santo,BRA,Brazil,211.0,118.0,NaN
120367,122266,Tiago Splitter,1985-01-01,Joinville,Santa Catarina,BRA,Brazil,210.0,117.0,NaN
122496,124594,Caio Torres,1987-06-03,São Paulo,São Paulo,BRA,Brazil,206.0,125.0,NaN
122499,124597,Marcus Vinícius,1984-05-31,Rio de Janeiro,Rio de Janeiro,BRA,Brazil,207.0,104.0,NaN
122500,124598,Nenê Hilário,1982-09-13,São Carlos,São Paulo,BRA,Brazil,211.0,113.0,NaN
124118,126392,Leandro Vissotto,1983-04-30,São Paulo,São Paulo,BRA,Brazil,212.0,97.0,NaN
124119,126393,Lucão,1986-03-06,Colinas,Rio Grande do Sul,BRA,Brazil,209.0,101.0,NaN
130123,132780,Augusto Lima,1991-09-17,Rio de Janeiro,Rio de Janeiro,BRA,Brazil,206.0,118.0,NaN
130124,132781,Cristiano Felício,1992-07-07,Pouso Alegre,Minas Gerais,BRA,Brazil,208.0,125.0,NaN
130125,132782,Rafael Hettsheimeir,1986-06-16,Araçatuba,São Paulo,BRA,Brazil,208.0,120.0,NaN
130134,132792,Evandro,1990-07-17,Rio de Janeiro,Rio de Janeiro,BRA,Brazil,210.0,105.0,NaN
130257,132931,Guerra,1981-12-27,Ibirá,São Paulo,BRA,Brazil,207.0,106.0,NaN
130260,132934,Maurício Souza,1988-09-29,Iturama,Minas Gerais,BRA,Brazil,209.0,93.0,NaN

In [98]:
bios[bios['name'].str.contains(r'^[J|L]', case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
12,13,J. Defert,NaN,NaN,NaN,NaN,France,NaN,NaN,NaN
17,18,Jean-Philippe Gatien,1968-10-16,Alès,Gard,FRA,France,178.0,73.0,NaN
...,...,...,...,...,...,...,...,...,...,...
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145470,149197,Lee Chae-Eun,2006-04-11,NaN,NaN,NaN,Republic of Korea,NaN,NaN,NaN
145477,149204,Lyu Yixin,2000-05-15,NaN,NaN,NaN,People's Republic of China,NaN,NaN,NaN
145482,149209,Jiang Dongxu,1993-03-03,Harbin,Heilongjiang,CHN,People's Republic of China,NaN,NaN,NaN
145493,149220,Landysh Falyakhova,1998-08-31,Dva Polya Artash,Respublika Tatarstan,RUS,ROC,NaN,NaN,NaN

In [104]:
len(greater_210cm['name'])

150

# Adding/Removing Columns

In [105]:
#Vou continuar amanhã, vou revisar o que aprendi e aplicar em um projeto agora