# Getting Started

In [2]:
import pandas as pd
from matplotlib.dates import SUNDAY, FRIDAY

df= pd.DataFrame([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20],[21,22,23,24]], columns=['a','b','c','d'])

In [20]:
df

    a   b   c   d
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       6 non-null      int64
 1   b       6 non-null      int64
 2   c       6 non-null      int64
 3   d       6 non-null      int64
dtypes: int64(4)
memory usage: 324.0 bytes

In [15]:
df.describe()

               a          b          c          d
count   6.000000   6.000000   6.000000   6.000000
mean   11.000000  12.000000  13.000000  14.000000
std     7.483315   7.483315   7.483315   7.483315
min     1.000000   2.000000   3.000000   4.000000
25%     6.000000   7.000000   8.000000   9.000000
50%    11.000000  12.000000  13.000000  14.000000
75%    16.000000  17.000000  18.000000  19.000000
max    21.000000  22.000000  23.000000  24.000000

In [35]:
df.shape

(6, 4)

In [37]:
df.size

24

# Loading in Dataframes from Files

In [8]:
coffee = pd.read_csv('./warmup-data/coffee.csv')
results = pd.read_parquet('./data/results.parquet')
bios = pd.read_csv('./data/bios.csv')

In [40]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [50]:
results.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

# Acessing Data with Pandas

In [13]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [24]:
coffee.iloc[2:7,0:3]

         Day Coffee Type  Units Sold
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40

In [34]:
coffee.index = coffee["Day"]
(coffee.tail())

               Day Coffee Type  Units Sold
Day
Friday      Friday       Latte          35
Saturday  Saturday    Espresso          45
Saturday  Saturday       Latte          35
Sunday      Sunday    Espresso          45
Sunday      Sunday       Latte          35

In [43]:
coffee.loc["Friday":"Sunday"]

               Day Coffee Type  Units Sold
Day
Friday      Friday    Espresso          45
Friday      Friday       Latte          35
Saturday  Saturday    Espresso          45
Saturday  Saturday       Latte          35
Sunday      Sunday    Espresso          45
Sunday      Sunday       Latte          35

In [45]:
coffee.Day#podemos acessar os dados assim de uma coluna se for apenas uma palavra, se for duas podemos usar [] os brackets
coffee["Units Sold"]#Como nesse exemplo

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Thursday     40
Thursday     30
Friday       45
Friday       35
Saturday     45
Saturday     35
Sunday       45
Sunday       35
Name: Units Sold, dtype: int64

In [47]:
coffee.sort_values("Units Sold", ascending=False)

                 Day Coffee Type  Units Sold
Day
Saturday    Saturday    Espresso          45
Friday        Friday    Espresso          45
Sunday        Sunday    Espresso          45
Thursday    Thursday    Espresso          40
Wednesday  Wednesday    Espresso          35
Saturday    Saturday       Latte          35
Sunday        Sunday       Latte          35
Friday        Friday       Latte          35
Tuesday      Tuesday    Espresso          30
Thursday    Thursday       Latte          30
Monday        Monday    Espresso          25
Wednesday  Wednesday       Latte          25
Tuesday      Tuesday       Latte          20
Monday        Monday       Latte          15

In [54]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=[0,1])

                 Day Coffee Type  Units Sold
Day
Friday        Friday    Espresso          45
Saturday    Saturday    Espresso          45
Sunday        Sunday    Espresso          45
Thursday    Thursday    Espresso          40
Wednesday  Wednesday    Espresso          35
Friday        Friday       Latte          35
Saturday    Saturday       Latte          35
Sunday        Sunday       Latte          35
Tuesday      Tuesday    Espresso          30
Thursday    Thursday       Latte          30
Monday        Monday    Espresso          25
Wednesday  Wednesday       Latte          25
Tuesday      Tuesday       Latte          20
Monday        Monday       Latte          15

In [ ]:
#Também podemos interagir com o for, porem perdemos a performance da memoria é ficaria muito mais pesado
# for index, row in coffee.iterrows():
#     print(index)
#     print(row)
#     print("\n\n\n")